import React, { useState, useEffect, useCallback, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowDownRight, ArrowUpRight, ArrowRight, BarChart3, Radio, Layers3, Search, Settings2, RefreshCw, Play, Download, ExternalLink, Check, AlertTriangle, X, Upload, ChevronRight, Database, BookOpen, ShieldCheck, SlidersHorizontal, FileText, Globe2, CircleHelp, Pause, Plus, Zap, Menu } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, BarChart, Bar, Legend, LineChart, Line } from 'recharts';
import './style.css';

const NAV = [{id:'overview',label:'Overview',icon:Activity},{id:'signals',label:'Risk signals',icon:Radio},{id:'allocation',label:'Index allocation',icon:Layers3},{id:'sources',label:'Data sources',icon:Globe2},{id:'guide',label:'Workflow & guide',icon:BookOpen},{id:'settings',label:'Risk policy',icon:Settings2}];
const COLORS=['#246951','#db8151','#638caf','#9b85b0','#b69245','#80a89e','#d69da1','#6e8c3b','#807868','#587f8f'];
const pct=v=>(v*100).toFixed(2)+'%';
const signed=v=>(v>0?'+':'')+Number(v).toFixed(2);
const timeLabel=value=>value?new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—';
const dateLabel=value=>value?new Date(value).toLocaleString(): 'Not fetched';
const safeUrl=value=>/^https?:\/\//i.test(value||'')?value:null;

async function api(path, options={}){
  const token=sessionStorage.getItem('riskpulse-token')||'';
  const res=await fetch('/api'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),'X-RiskPulse-Token':token,...options.headers}});
  if(!res.ok){let detail;try{detail=(await res.json()).detail;}catch{detail=res.statusText;}
    throw new Error(typeof detail==='string'?detail:JSON.stringify(detail));}
  return res.json();
}
function App(){
  const [page,setPage]=useState('overview'),[mode,setMode]=useState('live'),[data,setData]=useState(null),[signals,setSignals]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[toast,setToast]=useState(''),[selected,setSelected]=useState(null),[modal,setModal]=useState(false),[menu,setMenu]=useState(false);
  const modeRef=useRef(mode);modeRef.current=mode;
  const load=useCallback(async()=>{
    const requested=modeRef.current;
    try{const [summary,rows]=await Promise.all([api('/overview?mode='+requested),api('/signals?mode='+requested+'&limit=500')]);if(modeRef.current===requested){setData(summary);setSignals(rows.items);setError('');}}
    catch(e){setError(e.message);}
  },[]);
  useEffect(()=>{setData(null);setSelected(null);load();const t=setInterval(load,5000);return()=>clearInterval(t);},[mode,load]);
  useEffect(()=>{const escape=e=>{if(e.key==='Escape'){setModal(false);setSelected(null);setMenu(false);}};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);}},[toast]);
  async function action(name,path,body={}){setBusy(name);try{const result=await api(path,{method:'POST',body:JSON.stringify(body)});await load();return result;}catch(e){setError(e.message);}finally{setBusy('');}}
  async function replay(reset=false,count=null){setBusy('replay');try{const r=await api('/replay',{method:'POST',body:JSON.stringify({reset,count})});if(mode!=='replay')setMode('replay');else await load();setToast(r.ingested+' synthetic items processed');}catch(e){setError(e.message);}finally{setBusy('');}}
  async function exportData(format){try{const res=await fetch('/api/export?mode='+mode+'&format='+format,{headers:{'X-RiskPulse-Token':sessionStorage.getItem('riskpulse-token')||''}});if(!res.ok)throw new Error('Export failed');const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='riskpulse_signals_'+mode+'.'+format;a.click();URL.revokeObjectURL(url);}catch(e){setError(e.message);}}
  const title=NAV.find(n=>n.id===page)?.label;
  const context={data,signals,mode,busy,selected,setSelected,action,replay,exportData,setModal,load,setToast,setError};
  return <div className="app-shell">
    <aside className={'sidebar '+(menu?'open':'')}>
      <div className="brand"><img src="/favicon.svg" alt=""/><span>RiskPulse<small>FINANCIAL INTELLIGENCE</small></span></div>
      <div className="workspace"><span className="workspace-logo">RP</span><div>Research workspace<small>Code to Connect 2026</small></div></div>
      <div className="nav-label">WORKSPACE</div>
      <nav>{NAV.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>{setPage(n.id);setMenu(false);}}><n.icon size={18}/>{n.label}{page===n.id&&<ChevronRight size={15}/>}</button>)}</nav>
      <div className="sidebar-note"><ShieldCheck size={22}/><strong>Every signal has a source</strong><p>Inspect the text, model and event evidence behind an allocation.</p><button onClick={()=>setPage('guide')}>Explore the workflow <ArrowRight size={15}/></button></div>
      <div className="sidebar-bottom"><span className="avatar">TS</span><div>Tanish Singh<small>NIT Raipur</small></div><span className="version">v1.0</span></div>
    </aside>
    <main>
      <header><div className="breadcrumbs"><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation"><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="header-right"><span className={'connection '+(error?'bad':'')}><i/>{error?'Connection issue':data?'API connected':'Connecting'}</span><a href="/docs" target="_blank" rel="noreferrer">API docs <ExternalLink size={13}/></a><span className="avatar small">TS</span></div></header>
      <div className="main-content">
        <div className="page-heading"><div><div className="eyebrow">RISK INTELLIGENCE / MODULE A</div><h1>{title}</h1><p>{page==='overview'?'Financial text signals and a transparent mock index.':page==='signals'?'Inspect source text, classifications and signal evidence.':page==='allocation'?'Track sentiment-driven allocations across ten stocks.':page==='sources'?'Monitor live connectors and publication timestamps.':page==='settings'?'Control signal quality, weight limits and turnover.':'Understand the engine and prepare your demonstration.'}</p></div><div className="heading-actions"><button className="button" onClick={()=>setModal(true)}><Plus size={16}/> Analyse text</button><button className="button primary" disabled={!!busy} onClick={()=>mode==='live'?action('refresh','/refresh',{source_ids:['bbc_business','apple_newsroom','microsoft_blog']}):replay(false,1)}>{busy?<RefreshCw size={16} className="spin"/>:mode==='live'?<RefreshCw size={16}/>:<Play size={16}/>} {mode==='live'?'Refresh sources':'Next replay event'}</button></div></div>
        <div className="mode-strip"><div className="mode-toggle"><button className={mode==='live'?'chosen':''} onClick={()=>setMode('live')}><Globe2 size={14}/> Live feeds</button><button className={mode==='replay'?'chosen':''} onClick={()=>setMode('replay')}><Play size={14}/> Synthetic replay</button></div><div className="mode-explanation">{mode==='replay'?<><span className="pill amber">SYNTHETIC DATA</span> Fictional events. Separate portfolio.</>:<><span className="pill green">LIVE SOURCES</span> Publication times determine freshness.</>}</div><div className="mode-last">Updated {timeLabel(data?.server_time)}</div></div>
        {error&&<div className="error-banner"><AlertTriangle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
        {data?<>{page==='overview'&&<Overview {...context} onNavigate={setPage}/>} {page==='signals'&&<Signals {...context}/>} {page==='allocation'&&<Allocation {...context}/>} {page==='sources'&&<Sources {...context}/>} {page==='settings'&&<Policy {...context}/>} {page==='guide'&&<Guide/>}</>:<div className="loading"><RefreshCw size={28} className="spin"/>Connecting to the risk engine…{error&&<ConnectionPanel reload={load}/>}</div>}
        <footer>RiskPulse research prototype <span>Mock allocation · Impact scores are heuristic severity estimates · No performance forecast</span></footer>
      </div>
    </main>
    {modal&&<TextModal {...context} close={()=>setModal(false)}/>}
    {selected&&<SignalDetail signal={selected} close={()=>setSelected(null)}/>}
    {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
  </div>;
}
function Metric({label,value,description,icon:Icon,tone=''}){return <div className="metric"><div className="metric-label">{label}<Icon size={18}/></div><div className={'metric-value '+tone}>{value}</div><div className="metric-description">{description}</div></div>;}
function Overview({data,signals,mode,busy,replay,selected,setSelected,onNavigate}){
  const positive=data.distribution.positive,negative=data.distribution.negative,total=data.counts.signals;
  const charts=data.history.map((h,i)=>({step:i,time:timeLabel(h.created_at),...Object.fromEntries(Object.entries(h.after).map(([k,v])=>[k,v*100]))}));
  const maxWeight=Math.max(...Object.values(data.weights));
  return <>
    <div className="metrics"><Metric label="TEXTS PROCESSED" value={data.counts.articles} description={mode==='live'?'Ingested from live sources':'Fictional replay items'} icon={FileText}/><Metric label="MEAN SENTIMENT" value={signed(data.mean_sentiment)} description={positive+' positive / '+negative+' negative signals'} icon={Activity} tone={data.mean_sentiment>0?'positive':data.mean_sentiment<0?'negative':''}/><Metric label="HIGH-IMPACT SIGNALS" value={data.high_impact} description="Estimated severity of 8 or higher" icon={Zap}/><Metric label="INDEX ALLOCATION" value={pct(data.allocation_total)} description={'10 stocks · largest weight '+pct(maxWeight)} icon={Layers3}/></div>
    {!total&&<div className="start-banner"><div><Radio size={22}/><span><strong>Your index starts at equal weight</strong><p>{mode==='live'?'Refresh sources to analyse public financial headlines and company announcements.':'Load the synthetic scenario to inspect the complete workflow.'}</p></span></div><button className="button" disabled={!!busy} onClick={()=>replay(true)}>Run synthetic scenario <ArrowRight size={16}/></button></div>}
    <div className="overview-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Allocation over time</h2><p>Actual saved portfolio snapshots</p></div><span className="pill neutral">WEIGHT %</span></div>{charts.length>1?<div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={charts} margin={{top:20,right:20,left:-20,bottom:0}}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e8ece7"/><XAxis dataKey="step" tick={{fontSize:11}} tickLine={false} axisLine={false} label={{value:'Rebalance snapshot',position:'insideBottomRight',offset:-3,fontSize:11}}/><YAxis tick={{fontSize:11}} tickLine={false} axisLine={false} unit="%" domain={['auto','auto']}/><Tooltip formatter={(v)=>Number(v).toFixed(2)+'%'}/>{['NVDA','JPM','AAPL'].map((ticker,i)=><Area key={ticker} type="monotone" dataKey={ticker} stroke={COLORS[i]} fill={COLORS[i]} fillOpacity={.04} strokeWidth={2.5}/>)}</AreaChart></ResponsiveContainer></div>:<div className="chart-empty"><BarChart3 size={34}/><strong>Allocation history will appear here</strong><p>New eligible signals create a saved rebalance.</p></div>}<div className="chart-legend">{['NVDA','JPM','AAPL'].map((t,i)=><span key={t}><i style={{background:COLORS[i]}}/>{t}</span>)}<button onClick={()=>onNavigate('allocation')}>All stocks <ArrowRight size={14}/></button></div></section>
      <section className="panel index-panel"><div className="panel-heading"><div><h2>Current index</h2><p>Sentiment-adjusted weights</p></div><Layers3 size={20}/></div><div className="weight-list">{data.universe.map((s,i)=><div className="weight-row" key={s.ticker}><span className="ticker-icon" style={{background:COLORS[i]+'18',color:COLORS[i]}}>{s.ticker.slice(0,2)}</span><div className="weight-name"><strong>{s.ticker}</strong><small>{s.company}</small></div><span className="weight-bar"><i style={{width:Math.max(4,data.weights[s.ticker]/data.policy.max_weight*100)+'%',background:COLORS[i]}}/></span><strong className="mono">{pct(data.weights[s.ticker])}</strong></div>)}</div></section></div>
    <div className="overview-bottom"><section className="panel"><div className="panel-heading"><div><h2>Latest risk signals</h2><p>Click a signal to inspect its evidence</p></div><button className="text-button" onClick={()=>onNavigate('signals')}>View all <ArrowRight size={14}/></button></div><SignalTable signals={signals.slice(0,6)} onSelect={setSelected}/></section><section className="panel engine-panel"><div className="panel-heading"><h2>Engine status</h2><ShieldCheck size={20}/></div><div className="engine-badge"><i className={data.model.loading?'loading-dot':''}/>{data.model.loading?'Loading FinBERT':data.model.active==='finbert'?'FinBERT active':'Financial lexicon fallback'}</div><p className="engine-description">{data.model.active==='finbert'?'Financial language model. Sentiment equals P(positive) − P(negative).':'Transparent rule-based sentiment. FinBERT becomes active after its dependencies and weights load.'}</p><div className="engine-facts"><div><span>Event classifier</span><strong>Auditable rules</strong></div><div><span>Impact estimate</span><strong>Heuristic / 1–10</strong></div><div><span>Min. confidence</span><strong>{pct(data.policy.min_confidence)}</strong></div><div><span>Turnover limit</span><strong>{pct(data.policy.max_turnover)}</strong></div><div><span>News half-life</span><strong>{data.policy.half_life_hours} hours</strong></div></div>{data.model.model_error&&<div className="small-warning">Model loading failed. Open Workflow & guide for setup steps.</div>}<button className="text-button" onClick={()=>onNavigate('settings')}>Manage policy <ArrowRight size={14}/></button></section></div>
  </>;
}
function SignalTable({signals,onSelect}){return signals.length?<div className="table-scroll"><table className="signal-table"><thead><tr><th>SOURCE TEXT</th><th>ASSET</th><th>SENTIMENT</th><th>EVENT</th><th>IMPACT</th></tr></thead><tbody>{signals.map(s=><tr key={s.id} onClick={()=>onSelect(s)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&onSelect(s)}><td><div className="headline">{s.title}</div><small>{s.source} · {timeLabel(s.published_at)}</small></td><td><span className="ticker-label">{s.ticker||'GLOBAL'}</span></td><td><span className={'sentiment '+s.sentiment_label}>{s.sentiment_score>0?<ArrowUpRight size={13}/>:s.sentiment_score<0?<ArrowDownRight size={13}/>:null}{signed(s.sentiment_score)}</span></td><td><span className="event-label">{s.event_classification}</span></td><td><span className={'impact '+(s.impact_score>=8?'high':'')}>{s.impact_score}<small>/10</small></span></td></tr>)}</tbody></table></div>:<div className="empty"><Radio size={26}/><p>No signals in this workspace yet.</p></div>;}
function Signals({signals,setSelected,exportData,mode,load,setToast,setError}){
  const [search,setSearch]=useState(''),[ticker,setTicker]=useState('all'),[sentiment,setSentiment]=useState('all'),[importing,setImporting]=useState(false);
  const file=useRef(null);
  const filtered=signals.filter(s=>(ticker==='all'||s.ticker===ticker)&&(sentiment==='all'||s.sentiment_label===sentiment)&&(s.title+' '+s.source+' '+s.event_classification).toLowerCase().includes(search.toLowerCase()));
  async function upload(e){const f=e.target.files[0];if(!f)return;setImporting(true);try{const form=new FormData();form.append('file',f);const r=await api('/import?mode='+mode,{method:'POST',body:form});setToast(r.ingested+' records imported, '+r.duplicates+' duplicates');await load();}catch(err){setError(err.message);}finally{setImporting(false);e.target.value='';}}
  return <section className="panel"><div className="toolbar"><label className="search-box"><Search size={16}/><input aria-label="Search signals" placeholder="Search headlines, sources or events…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter ticker" value={ticker} onChange={e=>setTicker(e.target.value)}><option value="all">All assets</option>{[...new Set(signals.map(s=>s.ticker).filter(Boolean))].sort().map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter sentiment" value={sentiment} onChange={e=>setSentiment(e.target.value)}><option value="all">All sentiment</option>{['positive','neutral','negative'].map(s=><option key={s}>{s}</option>)}</select><button className="button" onClick={()=>file.current.click()} disabled={importing}><Upload size={15}/> Import</button><input hidden ref={file} type="file" accept=".csv,.json" onChange={upload}/><button className="button" onClick={()=>exportData('csv')}><Download size={15}/> CSV</button><button className="button" onClick={()=>exportData('json')}>JSON</button></div><div className="result-count">{filtered.length} signals · {mode==='replay'?'Synthetic replay':'Live source and analyst records'} · Import limit: 100 records / 256 KB</div><SignalTable signals={filtered} onSelect={setSelected}/></section>;
}
function Allocation({data,mode,busy,action,replay}){
 const comparison=data.universe.map(s=>({ticker:s.ticker,baseline:10,current:data.weights[s.ticker]*100}));
 const history=data.history.map((h,i)=>({snapshot:i,...Object.fromEntries(Object.entries(h.after).map(([k,v])=>[k,v*100]))}));
 return <><div className="allocation-summary"><div><span className="eyebrow">MOCK INDEX</span><h2>10-stock sentiment index</h2><p>Equal-weight targets tilt with fresh, eligible sentiment. Turnover limits constrain each update.</p></div><div><strong>{pct(data.allocation_total)}</strong><span>Total allocation</span></div><div><strong>{pct(data.last_rebalance.turnover||0)}</strong><span>Last one-way turnover</span></div><button className="button" disabled={!!busy} onClick={()=>action('rebalance','/rebalance?mode='+mode)}>Recompute weights</button></div><section className="panel"><div className="panel-heading"><div><h2>Baseline and current allocation</h2><p>Baseline 10% per stock. Current weights include risk controls.</p></div></div><div className="chart allocation-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparison} margin={{top:15,right:30,left:0,bottom:10}}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="ticker" tick={{fontSize:12}}/><YAxis unit="%"/><Tooltip formatter={v=>Number(v).toFixed(2)+'%'}/><Legend/><Bar dataKey="baseline" name="Equal-weight baseline" fill="#d4ddd5" radius={[4,4,0,0]}/><Bar dataKey="current" name="Current allocation" fill="#2d7155" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="panel-heading"><div><h2>Weight history</h2><p>Every curve follows persisted snapshots</p></div>{mode==='replay'&&<button className="button" onClick={()=>replay(true)}>Reset and replay</button>}</div><div className="chart allocation-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={history} margin={{top:15,right:25,left:0,bottom:5}}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="snapshot"/><YAxis unit="%" domain={['auto','auto']}/><Tooltip formatter={v=>Number(v).toFixed(2)+'%'}/><Legend/>{data.universe.map((s,i)=><Line key={s.ticker} type="monotone" dataKey={s.ticker} stroke={COLORS[i]} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div></section><section className="panel"><div className="panel-heading"><h2>Latest rebalance evidence</h2></div><div className="table-scroll"><table><thead><tr><th>ASSET</th><th>BEFORE</th><th>CURRENT</th><th>CHANGE</th><th>ELIGIBLE SIGNALS</th><th>AGGREGATED SENTIMENT</th></tr></thead><tbody>{data.universe.map(s=>{const last=data.last_rebalance;return <tr key={s.ticker}><td><strong>{s.ticker}</strong><small>{s.company}</small></td><td className="mono">{pct(last.before?.[s.ticker]??.1)}</td><td className="mono">{pct(data.weights[s.ticker])}</td><td className="mono">{signed((data.weights[s.ticker]-(last.before?.[s.ticker]??.1))*100)} pp</td><td>{last.scores?.[s.ticker]?.count||0}</td><td>{signed(last.scores?.[s.ticker]?.score||0)}</td></tr>;})}</tbody></table></div><p className="panel-footnote">Policy-compliance updates can exceed the turnover limit when new mandatory weight limits require a correction.</p></section></>;
}
function Sources({data,busy,action}){return <><div className="sources-intro"><div><h2>Two independent text-source types</h2><p>Financial news and first-party company announcements feed the same risk engine. Headlines and summaries form the analysis text.</p></div><button className="button" disabled={!!busy} onClick={()=>action('polling','/polling',{enabled:!data.polling})}>{data.polling?<Pause size={16}/>:<Play size={16}/>} {data.polling?'Pause polling':'Enable polling'}</button></div><div className="source-grid">{data.sources.map(s=><section className="panel source-card" key={s.id}><div className="source-card-top"><span className="source-symbol"><Globe2 size={24}/></span><span className={'pill '+(s.status==='ok'?'green':s.status==='error'?'amber':'neutral')}>{s.status==='ok'?'CONNECTED':s.status==='error'?'FETCH ERROR':'NOT FETCHED'}</span></div><h2>{s.name}</h2><p>{s.type.replaceAll('_',' ')} · {s.kind.toUpperCase()}</p><dl><div><dt>Last check</dt><dd>{dateLabel(s.last_checked)}</dd></div><div><dt>Last success</dt><dd>{dateLabel(s.last_success)}</dd></div><div><dt>Returned / added</dt><dd>{s.items_returned??'—'} / {s.added??'—'}</dd></div><div><dt>Reliability coefficient</dt><dd>{s.reliability} (design assumption)</dd></div></dl>{s.error&&<div className="small-warning">{s.error}</div>}<div className="source-actions"><a href={s.url} target="_blank" rel="noreferrer">Source URL <ExternalLink size={13}/></a><button className="button" disabled={!!busy} onClick={()=>action('refresh','/refresh',{source_ids:[s.id]})}>Fetch now</button></div></section>)}</div><div className="info-note"><CircleHelp size={20}/><p>Automatic polling runs every {data.poll_seconds} seconds while the server is running. A 30-second manual cooldown protects feeds. GDELT can return 429 when rate-limited. Synthetic replay never fills a live source failure.</p></div></>;}
function Policy({data,load,setToast,setError}){
 const [policy,setPolicy]=useState(data.policy),[token,setToken]=useState(sessionStorage.getItem('riskpulse-token')||''),[saving,setSaving]=useState(false);
 const fields=[['sensitivity','Sentiment sensitivity','0.01–1.00. Larger values tilt weights more.',.01],['min_weight','Minimum stock weight','Fraction of portfolio. 0.02 means 2%.',.01],['max_weight','Maximum stock weight','Fraction of portfolio. 0.18 means 18%.',.01],['max_turnover','Maximum one-way turnover','0.10 means 10% of portfolio per update.',.01],['min_confidence','Minimum sentiment confidence','Low-confidence signals stay visible but do not tilt allocation.',.01],['min_sentiment','Minimum absolute sentiment','Ignore sentiment scores close to zero.',.01],['half_life_hours','News half-life (hours)','After this period, an article has half its original influence.',.5],['max_age_hours','Maximum signal age (hours)','Older news stays in history but stops influencing allocation.',1]];
 async function save(e){e.preventDefault();setSaving(true);try{await api('/policy',{method:'PUT',body:JSON.stringify(policy)});await load();setToast('Policy saved and both portfolios recomputed');}catch(err){setError(err.message);}finally{setSaving(false);}}
 return <div className="settings-grid"><form className="panel policy-form" onSubmit={save}><div className="panel-heading"><div><h2>Allocation controls</h2><p>Persisted policy applies to live and replay portfolios</p></div><SlidersHorizontal size={20}/></div><div className="form-grid">{fields.map(([key,label,help,step])=><label key={key}>{label}<input type="number" required step={step} value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/><small>{help}</small></label>)}</div><div className="form-footer"><button className="button" type="button" onClick={()=>setPolicy({sensitivity:.35,min_weight:.02,max_weight:.18,max_turnover:.10,half_life_hours:12,min_confidence:.55,min_sentiment:.08,max_age_hours:72})}>Restore default values</button><button className="button primary" disabled={saving}>Save policy</button></div></form><section className="panel token-panel"><h2>Connection token</h2><p>For local use, leave this empty. If you configured RISKPULSE_API_TOKEN on the server, enter it here.</p><input aria-label="API token" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Optional server API token"/><button className="button" onClick={()=>{sessionStorage.setItem('riskpulse-token',token);load();setToast('Connection token saved for this browser session');}}>Save connection token</button><hr/><h2>Current NLP backend</h2><p><strong>{data.model.active}</strong></p>{data.model.loading&&<p>FinBERT weights are loading in the background.</p>}{data.model.model_error&&<div className="small-warning">{data.model.model_error}</div>}<p>Event labels and impact scores use documented rules. Impact is a severity proxy.</p></section></div>;
}
function Guide(){return <div className="guide"><section className="panel"><h2>The processing workflow</h2><ol className="workflow-list"><li><strong>Ingest text</strong><p>Fixed public connectors fetch news headlines and company announcement summaries. CSV/JSON import supports additional datasets.</p></li><li><strong>Clean and deduplicate</strong><p>HTML stripping and normalized headline fingerprints prevent repeated processing of the same headline.</p></li><li><strong>Generate risk signals</strong><p>Company aliases identify assets. FinBERT produces sentiment probabilities. Event rules identify categories, and an auditable heuristic estimates impact.</p></li><li><strong>Apply allocation policy</strong><p>Eligible sentiment receives confidence, source and recency weights. Equal-weight targets tilt using an exponential transformation, then respect weight and turnover limits.</p></li><li><strong>Persist and inspect</strong><p>SQLite stores text, signals and every changed allocation. Export JSON/CSV or use the API at /docs.</p></li></ol></section><section className="panel guide-demo"><h2>A five-minute demonstration</h2><p>1. Explain the challenge and open Data sources.</p><p>2. Refresh live feeds and inspect a generated signal.</p><p>3. Switch to Synthetic replay and process one event.</p><p>4. Open Index allocation and explain the changed weight.</p><p>5. Inspect confidence, severity evidence and policy controls.</p><p>6. Show API docs, export and the reproducible README.</p><hr/><h2>FinBERT setup</h2><p>The default backend attempts to load ProsusAI/finbert after startup. Install the model dependencies with <code>pip install -r requirements-ml.txt</code>, then run <code>python scripts/setup_model.py</code>. Restart the server when setup finishes.</p><p>The first download needs internet. Cached inference runs locally on CPU. If unavailable, the UI identifies the financial lexicon fallback.</p><hr/><h2>Interpretation</h2><p>Text sentiment expresses tone. It does not predict future stock returns. Source reliability coefficients are policy assumptions. Event/impact rules require external validation for use beyond the hackathon.</p></section></div>;}
function TextModal({mode,close,load,setToast,setError}){
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[ticker,setTicker]=useState(''),[sending,setSending]=useState(false),[preview,setPreview]=useState(null),[localError,setLocalError]=useState('');
 async function send(save){setSending(true);setLocalError('');try{const r=await api(save?'/ingest':'/analyze',{method:'POST',body:JSON.stringify({title,body,mode,tickers:ticker?[ticker]:null,source:'Analyst input',source_type:'analyst_input'})});if(save){setToast(r.duplicate?'Duplicate headline skipped':'Text processed and allocation recomputed');await load();close();}else setPreview(r.signals);}catch(err){setLocalError(err.message);}finally{setSending(false);}}
 return <div className="modal-backdrop" onClick={close}><section role="dialog" aria-modal="true" aria-labelledby="text-title" className="modal" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2 id="text-title">Analyse financial text</h2><p>Workspace: {mode}. Manual input records its own source.</p></div><button className="icon-button" onClick={close} aria-label="Close"><X size={20}/></button></div><label>Headline<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} maxLength={1000} placeholder="Paste a financial headline"/></label><label>Body or context<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={12000} rows={5} placeholder="Optional supporting text"/></label><label>Company mapping<select value={ticker} onChange={e=>setTicker(e.target.value)}><option value="">Identify automatically</option>{['AAPL','MSFT','NVDA','AMZN','GOOGL','META','JPM','XOM','JNJ','WMT'].map(t=><option key={t}>{t}</option>)}</select></label>{preview&&<div className="preview-signals">{preview.map((s,i)=><div key={i}><strong>{s.ticker||'GLOBAL'}</strong><span className={'sentiment '+s.sentiment_label}>{signed(s.sentiment_score)}</span><span>{s.event_classification}</span><span>Impact {s.impact_score}/10</span></div>)}</div>}{localError&&<div className="small-warning">{localError}</div>}<div className="modal-actions"><button className="button" disabled={sending||title.trim().length<5} onClick={()=>send(false)}>Preview only</button><button className="button primary" disabled={sending||title.trim().length<5} onClick={()=>send(true)}>Save signal & rebalance</button></div></section></div>;
}
function SignalDetail({signal:s,close}){return <div className="modal-backdrop" onClick={close}><section role="dialog" aria-modal="true" aria-labelledby="signal-title" className="modal signal-detail" onClick={e=>e.stopPropagation()}><div className="modal-heading"><span className={'pill '+(s.mode==='replay'?'amber':'green')}>{s.mode==='replay'?'SYNTHETIC REPLAY':'LIVE / ANALYST RECORD'}</span><button className="icon-button" onClick={close} aria-label="Close signal"><X size={20}/></button></div><h2 id="signal-title">{s.title}</h2><p className="source-line">{s.source} · {dateLabel(s.published_at)}</p><div className="detail-metrics"><div><small>SENTIMENT</small><strong className={s.sentiment_label}>{signed(s.sentiment_score)}</strong></div><div><small>CONFIDENCE</small><strong>{pct(s.confidence)}</strong></div><div><small>IMPACT ESTIMATE</small><strong>{s.impact_score}<small>/10</small></strong></div></div><dl className="detail-list"><div><dt>Company / event</dt><dd>{s.ticker||'Global event'} / {s.event_classification}</dd></div><div><dt>Sentiment backend</dt><dd>{s.model_backend}</dd></div><div><dt>Entity context</dt><dd>{s.entity_scope}</dd></div><div><dt>Event evidence</dt><dd>{s.event_evidence.join(', ')||'No classified event phrase'}</dd></div><div><dt>Analysis latency</dt><dd>{s.latency_ms} ms</dd></div></dl><h3>Text analysed</h3><blockquote>{s.analysis_text}</blockquote><h3>Impact calculation</h3><p>Event baseline {s.impact_breakdown.event_baseline}; severity cues: {s.impact_breakdown.severity_cues.join(', ')||'none'}; sentiment adjustment: +{s.impact_breakdown.sentiment_adjustment}; mitigating cues: {s.impact_breakdown.mitigating_cues.join(', ')||'none'}. Clamped to 1–10.</p><p className="small-warning">{s.impact_breakdown.method}</p>{s.probabilities&&<><h3>Model probabilities</h3><div className="probabilities">{Object.entries(s.probabilities).map(([label,p])=><span key={label}>{label}: {pct(p)}</span>)}</div></>}{safeUrl(s.url)&&<a className="button" href={s.url} target="_blank" rel="noreferrer">Open original source <ExternalLink size={15}/></a>}</section></div>;}
function ConnectionPanel({reload}){const [token,setToken]=useState('');return <div style={{maxWidth:360,width:'100%'}}><label>Optional API token<input type="password" value={token} onChange={e=>setToken(e.target.value)}/></label><button className="button" style={{marginTop:12}} onClick={()=>{sessionStorage.setItem('riskpulse-token',token);reload();}}>Retry connection</button></div>;}
createRoot(document.getElementById('root')).render(<App/>);
